environment:
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"

matrix:
  fast_finish: true

cache:
  - '%PYTHON%\Lib\site-packages -> requirements.txt, tests\requirements.txt'
  - '%AppData%\pip-cache'

install:
  # install the latest Microsoft Visual C++ Redistributable for Visual Studio 2015-2019
  # (currently 14.24.28127.4) to support FH4 exception handling in the latest dimod
  # (see https://devblogs.microsoft.com/cppblog/making-cpp-exception-handling-smaller-x64/)
  - ps: |
      Invoke-WebRequest "https://aka.ms/vs/16/release/vc_redist.x64.exe" -OutFile vcredist.exe
      Start-Process -FilePath .\vcredist.exe -ArgumentList "/install /quiet /norestart /log vcredist.log" -NoNewWindow -Wait
      cat .\vcredist.log

build_script:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt -r tests\\requirements.txt --cache-dir %AppData%\\pip-cache"

before_test:
  - "%PYTHON%\\python.exe -m pip install ."

test_script:
  - "%PYTHON%\\python.exe -m unittest discover"
