version: 2.1

parameters:
  cache-generation:
    type: integer
    default: 2

orbs:
  win: circleci/windows@5.0
  codecov: codecov/codecov@3

environment:
  PIP_PROGRESS_BAR: 'off'

jobs:
  test-linux:
    parameters:
      python-version:
        type: string
      pip-constraints:
        type: string

    docker:
      - image: cimg/python:<< parameters.python-version >>

    steps:
      - checkout

      - restore_cache: &restore-cache-env
          key: v<< pipeline.parameters.cache-generation >>-pip-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: &create-virtualenv
          name: Create virtual environment
          command: |
            python -V
            python -m venv env

      - run: &install-requirements
          name: Install requirements
          command: |
            . env/bin/activate
            pip install -U pip
            pip install -r requirements.txt
            pip install -r tests/requirements.txt
            pip install wheel twine

      - save_cache: &save-cache-env
          key: v<< pipeline.parameters.cache-generation >>-pip-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - env

      - run: &build-package
          name: Build package
          command: env/bin/python setup.py sdist bdist_wheel

      - run: &install-package-with-constraints
          name: Install package (with constraints)
          command: |
            . env/bin/activate
            pip install . -c <(printf '%s\n' << parameters.pip-constraints >>)

      - run: &run-python-tests
          name: Run Python tests
          command: |
            . env/bin/activate
            coverage run -m unittest discover
            coverage xml

      - codecov/upload: &upload-python-code-coverage
          file: coverage.xml

  test-macos:
    parameters:
      python-version:
        type: string
      xcode:
        type: string
        default: "14.2.0"

    macos:
      xcode: << parameters.xcode >>

    steps:
      - checkout

      - run: &brew-install-pyenv
          name: Install pyenv
          command: brew install pyenv

      - restore_cache: &restore-cache-pyenv
          keys:
            - v<< pipeline.parameters.cache-generation >>-pyenv-{{ .Environment.CIRCLE_JOB }}-xcode-<< parameters.xcode >>

      - run: &pyenv-install-python
          name: Install python
          command: pyenv install << parameters.python-version >> -s

      - run: &pyenv-set-system-python
          name: Set system python
          command: |
            echo -e '\n\n# Initialize pyenv' >> ~/.bash_profile
            echo 'eval "$(pyenv init --path 2>/dev/null || true)"' >> ~/.bash_profile
            echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
            pyenv global << parameters.python-version >>

      - save_cache: &save-cache-pyenv
          key: v<< pipeline.parameters.cache-generation >>-pyenv-{{ .Environment.CIRCLE_JOB }}-xcode-<< parameters.xcode >>
          paths:
            - ~/.pyenv

      # install dependencies and cache them
      - restore_cache: *restore-cache-env

      - run: *create-virtualenv

      - run: *install-requirements

      - save_cache: *save-cache-env

      - run: &install-package
          name: Install package
          command: env/bin/pip install .

      - run: *run-python-tests

  test-windows:
    parameters:
      python-version:
        type: string

    executor:
      name: win/default

    steps:
      - checkout

      - run:
          name: Install python and create virtualenv
          shell: bash -eo pipefail
          command: |
            # resolve python MAJOR.MINOR version to latest MAJOR.MINOR.PATCH version available on NuGet
            full_version=$(
              curl -s 'https://azuresearch-usnc.nuget.org/query?q=python' \
              | jq -r '.data[] | select(.id == "python") .versions[] | .version' \
              | awk -F. -v ver='<< parameters.python-version >>' \
                  'index($0, ver".") == 1 && $3 >= m { m = $3; v = $0 } END { print v }'
            )
            nuget install python -Version "$full_version" -ExcludeVersion
            python/tools/python -V
            python/tools/python -m venv env

      - run:
          name: Install requirements
          command: |
            env\Scripts\activate.ps1
            pip install -U pip
            pip install -r requirements.txt -r tests\requirements.txt

      - run:
          name: Install package
          command: |
            env\Scripts\activate.ps1
            pip install .

      - run:
          name: Run tests
          command: |
            env\Scripts\activate.ps1
            coverage run -m unittest discover

  test-docs:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      - restore_cache:
          key: v<< pipeline.parameters.cache-generation >>-pip-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum "docs/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: *create-virtualenv

      - run: *install-requirements

      - run:
          name: Install docs requirements
          command: env/bin/pip install -r docs/requirements.txt

      - save_cache:
          key: v<< pipeline.parameters.cache-generation >>-pip-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum "docs/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - env

      - run: *install-package

      - run:
          name: Build docs
          command: |
            . env/bin/activate
            make -C docs/ html

      - store_artifacts:
          path: ./docs/build/html

      - run:
          name: Test docs
          command: |
            . env/bin/activate
            make -C docs/ doctest

      - run:
          name: Test links
          command: |
            . env/bin/activate
            make -C docs/ linkcheck

  pypi-deploy:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      - restore_cache: *restore-cache-env

      - run: *create-virtualenv

      - run: *install-requirements

      - save_cache: *save-cache-env

      - run: *build-package

      - store_artifacts:
          path: ./dist

      - run:
          name: Upload package to PyPI
          command: env/bin/twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" --skip-existing ./dist/*


workflows:
  test:
    jobs:
      - test-linux:
          name: test-linux-<< matrix.python-version >> | << matrix.pip-constraints >>
          matrix:
            parameters:
              python-version: &python-versions ["3.8", "3.9", "3.10", "3.11", "3.12"]
              pip-constraints:
                - "dimod==0.10.13"
                - "dimod~=0.10.0 dwave-preprocessing~=0.3.0 dwave-system~=1.0"
                - "dimod~=0.11.0 dwave-preprocessing~=0.4.0 dwave-system~=1.0"
                - "dimod~=0.12.0 dwave-preprocessing~=0.6.0 dwave-system~=1.0"
            exclude:
              # dimod < 0.12 not supported on py311+
              - python-version: "3.11"
                pip-constraints: "dimod==0.10.13"
              - python-version: "3.11"
                pip-constraints: "dimod~=0.10.0 dwave-preprocessing~=0.3.0 dwave-system~=1.0"
              - python-version: "3.11"
                pip-constraints: "dimod~=0.11.0 dwave-preprocessing~=0.4.0 dwave-system~=1.0"
              - python-version: "3.12"
                pip-constraints: "dimod==0.10.13"
              - python-version: "3.12"
                pip-constraints: "dimod~=0.10.0 dwave-preprocessing~=0.3.0 dwave-system~=1.0"
              - python-version: "3.12"
                pip-constraints: "dimod~=0.11.0 dwave-preprocessing~=0.4.0 dwave-system~=1.0"

      - test-macos:
          matrix:
            parameters:
              python-version: *python-versions

      - test-windows:
          matrix:
            parameters:
              python-version: *python-versions

      - test-docs

  deploy:
    jobs:
      - pypi-deploy:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*((\.dev|rc)([0-9]+)?)?$/
            branches:
              ignore: /.*/
